export const backgroundTokensLight = {
  red: "var(--color-red-300)",
  white: "var(--color-base-white)",
  black: "var(--color-base-black)",
  transparent: "var(--color-base-transparent)",
  "level-1": "var(--color-base-white)",
  "level-2": "var(--color-neutral-100)",
  "level-3": "var(--color-base-white)",
  "level-4": "#000000A3",
  "level-5": "var(--color-base-white)",
  input: "var(--color-white)",
  "input-disabled": "var(--color-neutral-100)",
  tooltip: "var(--color-neutral-700)",
  dialog: "var(--color-white)",
  card: "var(--color-white)",
  "neutral-rest": "var(--color-neutral-200)",
  "neutral-hover": "var(--color-neutral-300)",
  "neutral-pressed": "var(--color-neutral-400)",
  "neutral-disabled": "var(--color-neutral-100)",
  "neutral-subtle": "var(--color-neutral-100)",

  "accent-info-rest": "var(--color-blue-600)",
  "accent-info-hover": "var(--color-blue-500)",
  "accent-info-pressed": "var(--color-blue-700)",
  "accent-info-disabled": "var(--color-blue-50)",
  "accent-info-subtle": "var(--color-blue-100)",
  "accent-info-subtle-hover": "var(--color-blue-200)",
  "accent-info-subtle-pressed": "var(--color-blue-300)",
  "accent-info-subtle-disabled": "var(--color-blue-50)",
  "accent-success-rest": "var(--color-green-600)",
  "accent-success-hover": "var(--color-green-500)",
  "accent-success-pressed": "var(--color-green-700)",
  "accent-success-disabled": "var(--color-green-50)",
  "accent-success-subtle": "var(--color-green-100)",
  "accent-success-subtle-hover": "var(--color-green-200)",
  "accent-success-subtle-pressed": "var(--color-green-300)",
  "accent-success-subtle-disabled": "var(--color-green-50)",

  "accent-warning-rest": "var(--color-orange-600)",
  "accent-warning-hover": "var(--color-orange-500)",
  "accent-warning-pressed": "var(--color-orange-700)",
  "accent-warning-disabled": "var(--color-orange-50)",
  "accent-warning-subtle": "var(--color-orange-100)",
  "accent-warning-subtle-hover": "var(--color-orange-200)",
  "accent-warning-subtle-pressed": "var(--color-orange-300)",
  "accent-warning-subtle-disabled": "var(--color-orange-50)",

  "accent-error-rest": "var(--color-red-600)",
  "accent-error-hover": "var(--color-red-500)",
  "accent-error-pressed": "var(--color-red-700)",
  "accent-error-disabled": "var(--color-red-50)",
  "accent-error-subtle": "var(--color-red-100)",
  "accent-error-subtle-hover": "var(--color-red-200)",
  "accent-error-subtle-pressed": "var(--color-red-300)",
  "accent-error-subtle-disabled": "var(--color-red-50)",

  "accent-yellow-rest": "var(--color-yellow-600)",
  "accent-yellow-hover": "var(--color-yellow-500)",
  "accent-yellow-pressed": "var(--color-yellow-700)",
  "accent-yellow-disabled": "var(--color-yellow-50)",
  "accent-yellow-subtle": "var(--color-yellow-100)",
  "accent-yellow-subtle-hover": "var(--color-yellow-200)",
  "accent-yellow-subtle-pressed": "var(--color-yellow-300)",
  "accent-yellow-subtle-disabled": "var(--color-yellow-50)",

  "accent-violet-rest": "var(--color-violet-600)",
  "accent-violet-hover": "var(--color-violet-500)",
  "accent-violet-pressed": "var(--color-violet-700)",
  "accent-violet-disabled": "var(--color-violet-50)",
  "accent-violet-subtle": "var(--color-violet-100)",
  "accent-violet-subtle-hover": "var(--color-violet-200)",
  "accent-violet-subtle-disabled": "var(--color-violet-50)",

  "brand-rest": "var(--color-orange-600)",
  "brand-hover": "var(--color-orange-700)",
  "brand-pressed": "var(--color-orange-800)",
  "brand-disabled": "var(--color-orange-200)",
  // 'brand-disabled-strong': 'var(--color-orange-200)',

  "brand-subtle-rest": "var(--color-orange-100)",
  "brand-subtle-hover": "var(--color-orange-200)",
  "brand-subtle-pressed": "var(--color-orange-300)",
  "brand-subtle-disabled": "var(--color-orange-50)",

  "bg-selected-rest": "var(--color-orange-100)",
  "bg-selected-hover": "var(--color-orange-200)",
  "bg-selected-pressed": "var(--color-orange-300)",
  "bg-selected-disabled": "var(--color-orange-100)",

  "bg-selected-bold-rest": "var(--color-orange-600)",
  "bg-selected-bold-hover": "var(--color-orange-700)",
  "bg-selected-bold-pressed": "var(--color-orange-800)",
  "bg-selected-bold-disabled": "var(--color-orange-50)",
  "bg-selected-bold-disabled-strong": "var(--color-orange-100)",

  "table-header": "var(--color-neutral-100)",
  "table-body": "var(--color-white)",

  "table-header-overlay": "var(--color-transparent)",
  "table-header-overlay-hover": "var(--color-black-alpha-0.25)",
  "table-header-overlay-pressed": "var(--color-black-alpha-2.25)",

  "table-body-overlay": "var(--color-transparent)",
  "table-body-overlay-hover": "var(--color-black-alpha-0.25)",
  "table-body-overlay-pressed": "var(--color-black-alpha-2.25)",

  "segment-control-container": "var(--color-neutral-200)",
  "segment-control-item": "var(--color-transparent)",
  "segment-control-item-hover": "var(--color-neutral-100)",
  "segment-control-item-disabled": "var(--color-transparent)",
  "segment-control-item-selected": "var(--color-white)",
  "segment-control-item-selected-disabled": "var(--color-neutral-100)",

  "neutral-bold-rest": "var(--color-neutral-200)",
  "neutral-bold-hover": "var(--color-neutral-300)",
  "neutral-bold-pressed": "var(--color-neutral-400)",
  "neutral-bold-disabled": "var(--color-neutral-100)",

  "neutral-boldest-rest": "var(--color-neutral-400)",
  "neutral-boldest-hover": "var(--color-neutral-300)",
  "neutral-boldest-pressed": "var(--color-neutral-500)",
  "neutral-boldest-disabled": "var(--color-neutral-100)",
};

export const backgroundTokensDark = {
  red: "var(--color-red-700)",
  white: "var(--color-base-white)",
  black: "var(--color-base-black)",
  transparent: "var(--color-base-transparent)",
  "level-1": "var(--color-neutral-950)",
  "level-2": "var(--color-neutral-900)",
  "level-3": "var(--color-neutral-800)",
  "level-4": "#000000",
  "level-5": "var(--color-neutral-700)",

  input: "var(--color-neutral-950)",
  "input-disabled": "var(--color-neutral-900)",
  tooltip: "var(--color-neutral-400)",
  dialog: "var(--color-neutral-800)",
  card: "var(--color-neutral-800)",

  "neutral-rest": "var(--color-neutral-600)",
  "neutral-hover": "var(--color-neutral-500)",
  "neutral-pressed": "var(--color-neutral-400)",
  "neutral-disabled": "var(--color-neutral-700)",
  "neutral-subtle": "var(--color-neutral-700)",
  "accent-info-rest": "var(--color-blue-400)",
  "accent-info-hover": "var(--color-blue-500)",
  "accent-info-pressed": "var(--color-blue-300)",
  "accent-info-disabled": "var(--color-blue-950)",
  "accent-info-subtle": "var(--color-blue-900)",
  "accent-info-subtle-hover": "var(--color-blue-800)",
  "accent-info-subtle-pressed": "var(--color-blue-800)",
  "accent-info-subtle-disabled": "var(--color-blue-950)",
  "accent-success-rest": "var(--color-green-400)",
  "accent-success-hover": "var(--color-green-500)",
  "accent-success-pressed": "var(--color-green-300)",
  "accent-success-disabled": "var(--color-green-950)",
  "accent-success-subtle": "var(--color-green-900)",
  "accent-success-subtle-hover": "var(--color-green-800)",
  "accent-success-subtle-pressed": "var(--color-green-800)",
  "accent-success-subtle-disabled": "var(--color-green-950)",
  "accent-warning-rest": "var(--color-orange-400)",
  "accent-warning-hover": "var(--color-orange-500)",
  "accent-warning-pressed": "var(--color-orange-300)",
  "accent-warning-disabled": "var(--color-orange-950)",
  "accent-warning-subtle": "var(--color-orange-900)",
  "accent-warning-subtle-hover": "var(--color-orange-800)",
  "accent-warning-subtle-pressed": "var(--color-orange-800)",
  "accent-warning-subtle-disabled": "var(--color-orange-950)",
  "accent-error-rest": "var(--color-red-400)",
  "accent-error-hover": "var(--color-red-500)",
  "accent-error-pressed": "var(--color-red-300)",
  "accent-error-disabled": "var(--color-red-950)",
  "accent-error-subtle": "var(--color-red-900)",
  "accent-error-subtle-hover": "var(--color-red-800)",
  "accent-error-subtle-pressed": "var(--color-red-800)",
  "accent-error-subtle-disabled": "var(--color-red-950)",
  "accent-yellow-rest": "var(--color-yellow-400)",
  "accent-yellow-hover": "var(--color-yellow-500)",
  "accent-yellow-pressed": "var(--color-yellow-300)",
  "accent-yellow-disabled": "var(--color-yellow-950)",
  "accent-yellow-subtle": "var(--color-yellow-100)",
  "accent-yellow-subtle-hover": "var(--color-yellow-800)",
  "accent-yellow-subtle-pressed": "var(--color-yellow-800)",
  "accent-yellow-subtle-disabled": "var(--color-yellow-950)",
  "accent-violet-rest": "var(--color-violet-400)",
  "accent-violet-hover": "var(--color-violet-500)",
  "accent-violet-pressed": "var(--color-violet-300)",
  "accent-violet-disabled": "var(--color-violet-950)",
  "accent-violet-subtle": "var(--color-violet-900)",
  "accent-violet-subtle-hover": "var(--color-violet-800)",
  "accent-violet-subtle-disabled": "var(--color-violet-950)",

  "brand-rest": "var(--color-orange-400)",
  "brand-hover": "var(--color-orange-300)",
  "brand-pressed": "var(--color-orange-700)",
  "brand-disabled": "var(--color-orange-900)",
  // 'brand-disabled-strong': 'var(--color-orange-900)',
  "brand-subtle-rest": "var(--color-orange-950)",
  "brand-subtle-hover": "var(--color-orange-950)",
  "brand-subtle-pressed": "var(--color-orange-800)",
  "brand-subtle-disabled": "var(--color-orange-900)",

  "bg-selected-rest": "var(--color-orange-900)",
  "bg-selected-hover": "var(--color-orange-800)",
  "bg-selected-pressed": "var(--color-orange-950)",
  "bg-selected-disabled": "var(--color-orange-900)",

  "bg-selected-bold-rest": "var(--color-orange-400)",
  "bg-selected-bold-hover": "var(--color-orange-300)",
  "bg-selected-bold-pressed": "var(--color-orange-700)",
  "bg-selected-bold-disabled": "var(--color-orange-950)",
  "bg-selected-bold-disabled-strong": "var(--color-orange-900)",

  "table-header": "var(--color-neutral-900)",
  "table-body": "var(--color-neutral-800)",

  "table-header-overlay": "var(--color-transparent)",
  "table-header-overlay-hover": "var(--color-white-alpha-0.25)",
  "table-header-overlay-pressed": "var(--color-white-alpha-2.25)",

  "table-body-overlay": "var(--color-transparent)",
  "table-body-overlay-hover": "var(--color-white-alpha-0.25)",
  "table-body-overlay-pressed": "var(--color-white-alpha-2.25)",

  "segment-control-container": "var(--color-neutral-800)",
  "segment-control-item": "var(--color-transparent)",
  "segment-control-item-hover": "var(--color-neutral-500)",
  "segment-control-item-disabled": "var(--color-transparent)",
  "segment-control-item-selected": "var(--color-neutral-600)",
  "segment-control-item-selected-disabled": "var(--color-neutral-800)",

  "neutral-bold-rest": "var(--color-neutral-700)",
  "neutral-bold-hover": "var(--color-neutral-600)",
  "neutral-bold-pressed": "var(--color-neutral-500)",
  "neutral-bold-disabled": "var(--color-neutral-800)",

  "neutral-boldest-rest": "var(--color-neutral-500)",
  "neutral-boldest-hover": "var(--color-neutral-500)",
  "neutral-boldest-pressed": "var(--color-neutral-600)",
  "neutral-boldest-disabled": "var(--color-neutral-700)",
};

export const foregroundTokensLight = {
  white: "var(--color-base-white)",
  black: "var(--color-base-black)",
  transparent: "var(--color-base-transparent)",
  "neutral-main": "var(--color-neutral-900)",
  "neutral-main-static": "var(--color-neutral-900)",
  "neutral-subtle": "var(--color-neutral-600)",
  "neutral-subtlest": "var(--color-neutral-500)",
  "neutral-disabled": "var(--color-neutral-300)",
  "neutral-decoration": "var(--color-neutral-200)",
  "neutral-inverse": "var(--color-base-white)",
  "neutral-inverse-static": "var(--color-base-white)",
  "accent-info": "var(--color-blue-600)",
  "accent-info-strong": "var(--color-blue-800)",
  "accent-info-disabled": "var(--color-blue-300)",
  "accent-success": "var(--color-green-600)",
  "accent-success-strong": "var(--color-green-800)",
  "accent-success-disabled": "var(--color-green-300)",
  "accent-warning": "var(--color-orange-600)",
  "accent-warning-strong": "var(--color-orange-800)",
  "accent-warning-disabled": "var(--color-orange-300)",
  "accent-error": "var(--color-red-600)",
  "accent-error-strong": "var(--color-red-800)",
  "accent-error-disabled": "var(--color-red-300)",
  "accent-yellow": "var(--color-yellow-600)",
  "accent-yellow-strong": "var(--color-yellow-800)",
  "accent-yellow-disabled": "var(--color-yellow-400)",
  "accent-violet": "var(--color-violet-600)",
  "accent-violet-strong": "var(--color-violet-800)",
  "accent-violet-disabled": "var(--color-violet-300)",
  "link-rest": "var(--color-blue-600)",
  "link-hover": "var(--color-blue-500)",
  "link-pressed": "var(--color-blue-700)",
  "link-disabled": "var(--color-blue-300)",
  "brand-rest": "var(--color-orange-600)",
  "brand-rest-strong": "var(--color-orange-800)",
  "brand-hover": "var(--color-orange-500)",
  "brand-pressed": "var(--color-orange-700)",
  "brand-pressed-strong": "var(--color-orange-800)",
  "brand-disabled": "var(--color-orange-300)",
  "brand-disabled-strong": "var(--color-orange-100)",
  "btn-primary": "var(--color-base-white)",
  "btn-primary-disabled": "var(--color-orange-300)",
  checkbox: "var(--color-base-white)",
  "checkbox-disabled": "var(--color-base-white)",

  "selected-rest": "var(--color-orange-600)",
  "selected-hover": "var(--color-orange-500)",
  "selected-pressed": "var(--color-orange-700)",
  "selected-pressed-strong": "var(--color-orange-800)",
  "selected-disabled": "var(--color-orange-300)",
  "selected-disabled-strong": "var(--color-orange-100)",
  "selected-bold-rest": "var(--color-base-white)",
  "focus-ring": "var(--color-orange-600)",
};

export const foregroundTokensDark = {
  white: "var(--color-base-white)",
  black: "var(--color-base-black)",
  transparent: "var(--color-base-transparent)",
  "neutral-main": "var(--color-base-white)",
  "neutral-main-static": "var(--color-neutral-900)",
  "neutral-subtle": "var(--color-neutral-300)",
  "neutral-subtlest": "var(--color-neutral-400)",
  "neutral-disabled": "var(--color-neutral-500)",
  "neutral-decoration": "var(--color-neutral-600)",
  "neutral-inverse": "var(--color-neutral-900)",
  "neutral-inverse-static": "var(--color-base-white)",
  "accent-info": "var(--color-blue-400)",
  "accent-info-strong": "var(--color-blue-400)",
  "accent-info-disabled": "var(--color-blue-700)",
  "accent-success": "var(--color-green-400)",
  "accent-success-strong": "var(--color-green-400)",
  "accent-success-disabled": "var(--color-green-700)",
  "accent-warning": "var(--color-orange-400)",
  "accent-warning-strong": "var(--color-orange-300)",
  "accent-warning-disabled": "var(--color-orange-700)",
  "accent-error": "var(--color-red-400)",
  "accent-error-strong": "var(--color-red-300)",
  "accent-error-disabled": "var(--color-red-700)",
  "accent-yellow": "var(--color-yellow-400)",
  "accent-yellow-strong": "var(--color-yellow-300)",
  "accent-yellow-disabled": "var(--color-yellow-600)",
  "accent-violet": "var(--color-violet-400)",
  "accent-violet-strong": "var(--color-violet-300)",
  "accent-violet-disabled": "var(--color-violet-700)",
  "link-rest": "var(--color-blue-400)",
  "link-hover": "var(--color-blue-500)",
  "link-pressed": "var(--color-blue-300)",
  "link-disabled": "var(--color-blue-700)",
  "brand-rest": "var(--color-orange-400)",
  "brand-rest-strong": "var(--color-orange-300)",
  "brand-hover": "var(--color-orange-500)",
  "brand-pressed": "var(--color-orange-300)",
  "brand-pressed-strong": "var(--color-orange-400)",
  "brand-disabled": "var(--color-orange-600)",
  "brand-disabled-strong": "var(--color-orange-900)",
  "btn-primary": "var(--color-neutral-900)",
  "btn-primary-disabled": "var(--color-orange-700)",
  checkbox: "var(--color-neutral-900)",
  "checkbox-disabled": "var(--color-neutral-900)",

  "selected-rest": "var(--color-orange-400)",
  "selected-hover": "var(--color-orange-500)",
  "selected-pressed": "var(--color-orange-300)",
  "selected-pressed-strong": "var(--color-orange-400)",
  "selected-disabled": "var(--color-orange-700)",
  "selected-disabled-strong": "var(--color-orange-900)",
  "selected-bold-rest": "var(--color-neutral-900)",
  "focus-ring": "var(--color-orange-400)",
};

const borderTokensLight = {
  selected: "var(--color-orange-600)",
  "selected-disabled": "var(--color-orange-300)",
  "segment-control": "var(--color-base-transparent)",
  input: "var(--color-neutral-300)",
  "input-active": "var(--color-orange-600)",
  "input-disabled": "var(--color-neutral-200)",
  card: "var(--color-neutral-200)",
  dialog: "var(--color-neutral-200)",
  table: "var(--color-neutral-200)",
  neutral: "var(--color-neutral-200)",
  "neutral-light": "var(--color-neutral-100)",
  "neutral-strong": "var(--color-neutral-300)",
  "neutral-strongest": "var(--color-neutral-400)",
  "neutral-dark": "var(--color-neutral-900)",
  "inverse-static": "var(--color-white)",
  inverse: "var(--color-white)",
  active: "var(--color-orange-600)",
  "active-strong": "var(--color-orange-800)",
  "active-light": "var(--color-orange-300)",
  info: "var(--color-blue-600)",
  "info-strong": "var(--color-blue-800)",
  "info-light": "var(--color-blue-300)",
  error: "var(--color-red-600)",
  "error-strong": "var(--color-red-800)",
  "error-light": "var(--color-red-300)",
  warning: "var(--color-orange-600)",
  "warning-strong": "var(--color-orange-800)",
  "warning-light": "var(--color-orange-300)",
  success: "var(--color-green-600)",
  "success-strong": "var(--color-green-800)",
  "success-light": "var(--color-green-300)",
  yellow: "var(--color-yellow-600)",
  "yellow-strong": "var(--color-yellow-800)",
  "yellow-light": "var(--color-yellow-400)",
  violet: "var(--color-violet-600)",
  "violet-strong": "var(--color-violet-800)",
  "violet-light": "var(--color-violet-300)",
};

const borderTokensDark = {
  selected: "var(--color-orange-400)",
  "selected-disabled": "var(--color-orange-700)",
  "segment-control": "var(--color-neutral-700)",
  input: "var(--color-neutral-650)",
  "input-active": "var(--color-orange-400)",
  "input-disabled": "var(--color-neutral-700)",
  card: "var(--color-neutral-700)",
  dialog: "var(--color-neutral-700)",
  table: "var(--color-neutral-700)",
  neutral: "var(--color-neutral-700)",
  "neutral-light": "var(--color-neutral-800)",
  "neutral-strong": "var(--color-neutral-600)",
  "neutral-strongest": "var(--color-neutral-500)",
  "neutral-dark": "var(--color-white)",
  "inverse-static": "var(--color-white)",
  inverse: "var(--color-neutral-900)",
  active: "var(--color-orange-400)",
  "active-strong": "var(--color-orange-300)",
  "active-light": "var(--color-orange-700)",
  info: "var(--color-blue-400)",
  "info-strong": "var(--color-blue-300)",
  "info-light": "var(--color-blue-700)",
  error: "var(--color-red-400)",
  "error-strong": "var(--color-red-300)",
  "error-light": "var(--color-red-700)",
  warning: "var(--color-orange-400)",
  "warning-strong": "var(--color-orange-300)",
  "warning-light": "var(--color-orange-700)",
  success: "var(--color-green-400)",
  "success-strong": "var(--color-green-300)",
  "success-light": "var(--color-green-700)",
  yellow: "var(--color-yellow-400)",
  "yellow-strong": "var(--color-yellow-300)",
  "yellow-light": "var(--color-yellow-600)",
  violet: "var(--color-violet-400)",
  "violet-strong": "var(--color-violet-300)",
  "violet-light": "var(--color-violet-700)",
};

export const bgTokensTheme = {
  light: backgroundTokensLight,
  dark: backgroundTokensDark,
};

export const fgTokensTheme = {
  light: foregroundTokensLight,
  dark: foregroundTokensDark,
};

export const borderTokensTheme = {
  light: borderTokensLight,
  dark: borderTokensDark,
};
